name: "Publish site"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
      - pagination
jobs:
  ema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.garnix.io https://cache.nixos.org/
      - name: Cache deps and build sources 🔧
        run: |
          nix run .#tailwind -- --help
          nix build -j 4
      - name: Generate HTML 🔧
        run: |
          mkdir ./output
          export TARGET=$(pwd)/output
          nix run .#tailwind -- -o static/tailwind.css 'src/**/*.hs' 
          ./result/bin/NixHaskellIndex gen $TARGET
      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
          cname: nixpkgs.haskell.page
