name: "Publish site"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
  pull_request:
jobs:
  www:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system: [x86_64-linux, aarch64-darwin]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - run: om ci
